RESOURCES = [
    'Food',
    'Lumber',
    'Stone',
    'Crystal',
    'Chrysotile',
    'Furs',
    'Copper',
    'Iron',
    'Aluminium',
    'Cement',
    'Coal',
    'Oil',
    'Uranium',
    'Steel',
    'Titanium',
    'Alloy',
    'Polymer',
    'Iridium',
    'Helium_3',
]


SPACE_MISSIONS = [
    'space-moon_mission',
    'space-red_mission',
    'space-hell_mission',
    'space-sun_mission',
    'space-gas_mission',
    'space-gas_moon_mission',
    'space-belt_mission',
    'space-dwarf_mission'
]


BUILDING_NAMES = {
    "city-food": "Gather Food",
    "city-lumber": "Gather Lumber",
    "city-stone": "Gather Stone",
    "city-chrysotile": "Gather Chrysotile",
    "city-slaughter": "Slaughter the Weak",
    "city-horseshoe": "Horseshoe",
    "city-slave_market": "Slave Market",
    "city-s_alter": "Sacrificial Altar",
    "city-basic_housing": "Cabin",
    "city-cottage": "Cottage",
    "city-apartment": "Apartment",
    "city-lodge": "Lodge",
    "city-smokehouse": "Smokehouse",
    "city-soul_well": "Soul Well",
    "city-slave_pen": "Slave Pen",
    "city-transmitter": "Transmitter",
    "city-captive_housing": "Captive Housing",
    "city-farm": "Farm",
    "city-compost": "Compost Heap",
    "city-mill": "Windmill",
    "city-windmill": "Windmill (Evil)",
    "city-silo": "Grain Silo",
    "city-assembly": "Assembly",
    "city-garrison": "Barracks",
    "city-hospital": "Hospital",
    "city-boot_camp": "Boot Camp",
    "city-shed": "Shed",
    "city-storage_yard": "Freight Yard",
    "city-warehouse": "Container Port",
    "city-bank": "Bank",
    "city-pylon": "Pylon",
    "city-conceal_ward": "Conceal Ward (Witch Hunting)",
    "city-lumber_yard": "Lumber Yard",
    "city-sawmill": "Sawmill",
    "city-rock_quarry": "Rock Quarry",
    "city-cement_plant": "Cement Plant",
    "city-foundry": "Foundry",
    "city-factory": "Factory",
    "city-nanite_factory": "Nanite Factory",
    "city-smelter": "Smelter",
    "city-metal_refinery": "Metal Refinery",
    "city-mine": "Mine",
    "city-coal_mine": "Coal Mine",
    "city-oil_well": "Oil Derrick",
    "city-oil_depot": "Fuel Depot",
    "city-trade": "Trade Post",
    "city-wharf": "Wharf",
    "city-tourist_center": "Tourist Center",
    "city-amphitheatre": "Amphitheatre",
    "city-casino": "Casino",
    "city-temple": "Temple",
    "city-shrine": "Shrine",
    "city-meditation": "Meditation Chamber",
    "city-university": "University",
    "city-library": "Library",
    "city-wardenclyffe": "Wardenclyffe",
    "city-biolab": "Bioscience Lab",
    "city-coal_power": "Coal Powerplant",
    "city-oil_power": "Oil Powerplant",
    "city-fission_power": "Fission Reactor",
    "city-mass_driver": "Mass Driver",

    "space-test_launch": "Space Test Launch",
    "space-satellite": "Space Satellite",
    "space-gps": "Space Gps",
    "space-propellant_depot": "Space Propellant Depot",
    "space-nav_beacon": "Space Navigation Beacon",

    "space-moon_mission": "Moon Mission",
    "space-moon_base": "Moon Base",
    "space-iridium_mine": "Moon Iridium Mine",
    "space-helium_mine": "Moon Helium-3 Mine",
    "space-observatory": "Moon Observatory",

    "space-red_mission": "Red Mission",
    "space-spaceport": "Red Spaceport",
    "space-red_tower": "Red Space Control",
    "space-captive_housing": "Red Captive Housing (Cataclysm)",
    "space-terraformer": "Red Terraformer (Orbit Decay)",
    "space-atmo_terraformer": "Red Terraformer (Orbit Decay, Complete)",
    "space-terraform": "Red Terraform (Orbit Decay)",
    "space-assembly": "Red Assembly (Cataclysm)",
    "space-living_quarters": "Red Living Quarters",
    "space-pylon": "Red Pylon (Cataclysm)",
    "space-vr_center": "Red VR Center",
    "space-garage": "Red Garage",
    "space-red_mine": "Red Mine",
    "space-fabrication": "Red Fabrication",
    "space-red_factory": "Red Factory",
    "space-nanite_factory": "Red Nanite Factory (Cataclysm)",
    "space-biodome": "Red Biodome",
    "space-red_university": "Red University (Orbit Decay)",
    "space-exotic_lab": "Red Exotic Materials Lab",
    "space-ziggurat": "Red Ziggurat",
    "space-space_barracks": "Red Marine Barracks",
    "space-horseshoe": "Red Horseshoe (Cataclysm)",

    "space-hell_mission": "Hell Mission",
    "space-geothermal": "Hell Geothermal Plant",
    "space-hell_smelter": "Hell Smelter",
    "space-spc_casino": "Hell Space Casino",
    "space-swarm_plant": "Hell Swarm Plant",

    "space-sun_mission": "Sun Mission",
    "space-swarm_control": "Sun Control Station",
    "space-swarm_satellite": "Sun Swarm Satellite",
    "space-jump_gate": "Sun Jump Gate",

    "space-gas_mission": "Gas Mission",
    "space-gas_mining": "Gas Helium-3 Collector",
    "space-gas_storage": "Gas Fuel Depot",
    "space-star_dock": "Gas Space Dock",
    "space-gas_moon_mission": "Gas Moon Mission",
    "space-outpost": "Gas Moon Mining Outpost",
    "space-drone": "Gas Moon Mining Drone",
    "space-oil_extractor": "Gas Moon Oil Extractor",

    "starDock-probes": "Space Dock Probe",
    "starDock-geck": "Space Dock G.E.C.K.",
    "starDock-seeder": "Space Dock Bioseeder Ship",
    "starDock-prep_ship": "Space Dock Prep Ship",
    "starDock-launch_ship": "Space Dock Launch Ship",

    "space-belt_mission": "Belt Mission",
    "space-space_station": "Belt Space Station",
    "space-elerium_ship": "Belt Elerium Mining Ship",
    "space-iridium_ship": "Belt Iridium Mining Ship",
    "space-iron_ship": "Belt Iron Mining Ship",

    "space-dwarf_mission": "Dwarf Mission",
    "space-elerium_contain": "Dwarf Elerium Storage",
    "space-e_reactor": "Dwarf Elerium Reactor",
    "space-world_collider": "Dwarf World Collider",
    "space-world_controller": "Dwarf World Collider (Complete)",
    "space-shipyard": "Dwarf Ship Yard",
    "space-mass_relay": "Dwarf Mass Relay",
    "space-m_relay": "Dwarf Mass Relay (Complete)",

    "space-titan_mission": "Titan Mission",
    "space-titan_spaceport": "Titan Spaceport",
    "space-electrolysis": "Titan Electrolysis",
    "space-hydrogen_plant": "Titan Hydrogen Plant",
    "space-titan_quarters": "Titan Habitat",
    "space-titan_mine": "Titan Mine",
    "space-storehouse": "Titan Storehouse",
    "space-titan_bank": "Titan Bank",
    "space-g_factory": "Titan Graphene Plant",
    "space-sam": "Titan SAM Site",
    "space-decoder": "Titan Decoder",
    "space-ai_core": "Titan AI Core",
    "space-ai_core2": "Titan AI Core (Complete)",
    "space-ai_colonist": "Titan AI Colonist",
    "space-enceladus_mission": "Enceladus Mission",
    "space-water_freighter": "Enceladus Water Freighter",
    "space-zero_g_lab": "Enceladus Zero Gravity Lab",
    "space-operating_base": "Enceladus Operational Base",
    "space-munitions_depot": "Enceladus Munitions Depot",
    "space-triton_mission": "Triton Mission",
    "space-fob": "Triton Forward Base",
    "space-lander": "Triton Troop Lander",
    "space-crashed_ship": "Triton Derelict Ship",
    "space-kuiper_mission": "Kuiper Mission",
    "space-orichalcum_mine": "Kuiper Orichalcum Mine",
    "space-uranium_mine": "Kuiper Uranium Mine",
    "space-neutronium_mine": "Kuiper Neutronium Mine",
    "space-elerium_mine": "Kuiper Elerium Mine",
    "space-eris_mission": "Eris Mission",
    "space-drone_control": "Eris Control Relay",
    "space-shock_trooper": "Eris Android Trooper",
    "space-tank": "Eris Tank",
    "space-digsite": "Eris Digsite",
    "tauceti-ringworld": "Tau Star Ringworld",
    "tauceti-matrix": "Tau Star Matrix",
    "tauceti-blue_pill": "Tau Star Blue Pill",
    "tauceti-goe_facility": "Tau Star Garden of Eden",

    "tauceti-home_mission": "Tau Mission",
    "tauceti-dismantle": "Tau Dismantle Ship",
    "tauceti-orbital_station": "Tau Orbital Station",
    "tauceti-colony": "Tau Colony",
    "tauceti-tau_housing": "Tau Housing",
    "tauceti-captive_housing": "Tau Captive Housing",
    "tauceti-pylon": "Tau Pylon",
    "tauceti-cloning_facility": "Tau Cloning",
    "tauceti-horseshoe": "Tau Horseshoe",
    "tauceti-assembly": "Tau Assembly",
    "tauceti-nanite_factory": "Tau Nanite Factory",
    "tauceti-tau_farm": "Tau High-Tech Farm",
    "tauceti-mining_pit": "Tau Mining Pit",
    "tauceti-excavate": "Tau Excavate",
    "tauceti-alien_outpost": "Tau Alien Outpost",
    "tauceti-jump_gate": "Tau Jump Gate",
    "tauceti-fusion_generator": "Tau Fusion Generator",
    "tauceti-repository": "Tau Repository",
    "tauceti-tau_factory": "Tau High-Tech Factory",
    "tauceti-infectious_disease_lab": "Tau Disease Lab",
    "tauceti-tauceti_casino": "Tau Casino",
    "tauceti-tau_cultural_center": "Tau Cultural Center",

    "tauceti-red_mission": "Tau Red Mission",
    "tauceti-orbital_platform": "Tau Red Orbital Platform",
    "tauceti-contact": "Tau Red Contact",
    "tauceti-introduce": "Tau Red Introduce",
    "tauceti-subjugate": "Tau Red Subjugate",
    "tauceti-jeff": "Tau Red Jeff",
    "tauceti-overseer": "Tau Red Overseer",
    "tauceti-womling_village": "Tau Red Womling Village",
    "tauceti-womling_farm": "Tau Red Womling Farm",
    "tauceti-womling_mine": "Tau Red Womling Mine",
    "tauceti-womling_fun": "Tau Red Womling Theater",
    "tauceti-womling_lab": "Tau Red Womling Lab",

    "tauceti-gas_contest": "Tau Gas Naming Contest",
    "tauceti-gas_contest-a1": "Tau Gas Name 1",
    "tauceti-gas_contest-a2": "Tau Gas Name 2",
    "tauceti-gas_contest-a3": "Tau Gas Name 3",
    "tauceti-gas_contest-a4": "Tau Gas Name 4",
    "tauceti-gas_contest-a5": "Tau Gas Name 5",
    "tauceti-gas_contest-a6": "Tau Gas Name 6",
    "tauceti-gas_contest-a7": "Tau Gas Name 7",
    "tauceti-gas_contest-a8": "Tau Gas Name 8",
    "tauceti-refueling_station": "Tau Gas Refueling Station",
    "tauceti-ore_refinery": "Tau Gas Ore Refinery",
    "tauceti-whaling_station": "Tau Gas Whale Processor",
    "tauceti-womling_station": "Tau Gas Womling Station",

    "tauceti-roid_mission": "Tau Belt Mission",
    "tauceti-patrol_ship": "Tau Belt Patrol Ship",
    "tauceti-mining_ship": "Tau Belt Extractor Ship",
    "tauceti-whaling_ship": "Tau Belt Whaling Ship",

    "tauceti-gas_contest2": "Tau Gas 2 Naming Contest",
    "tauceti-gas_contest-b1": "Tau Gas 2 Name 1",
    "tauceti-gas_contest-b2": "Tau Gas 2 Name 2",
    "tauceti-gas_contest-b3": "Tau Gas 2 Name 3",
    "tauceti-gas_contest-b4": "Tau Gas 2 Name 4",
    "tauceti-gas_contest-b5": "Tau Gas 2 Name 5",
    "tauceti-gas_contest-b6": "Tau Gas 2 Name 6",
    "tauceti-gas_contest-b7": "Tau Gas 2 Name 7",
    "tauceti-gas_contest-b8": "Tau Gas 2 Name 8",
    "tauceti-alien_station_survey": "Tau Gas 2 Alien Station (Survey)",
    "tauceti-alien_station": "Tau Gas 2 Alien Station",
    "tauceti-alien_space_station": "Tau Gas 2 Alien Space Station",
    "tauceti-matrioshka_brain": "Tau Gas 2 Matrioshka Brain",
    "tauceti-ignition_device": "Tau Gas 2 Ignition Device",
    "tauceti-ignite_gas_giant": "Tau Gas 2 Ignite Gas Giant",

    "interstellar-alpha_mission": "Alpha Centauri Mission",
    "interstellar-starport": "Alpha Starport",
    "interstellar-habitat": "Alpha Habitat",
    "interstellar-mining_droid": "Alpha Mining Droid",
    "interstellar-processing": "Alpha Processing Facility",
    "interstellar-fusion": "Alpha Fusion Reactor",
    "interstellar-laboratory": "Alpha Laboratory",
    "interstellar-exchange": "Alpha Exchange",
    "interstellar-g_factory": "Alpha Graphene Plant",
    "interstellar-warehouse": "Alpha Warehouse",
    "interstellar-int_factory": "Alpha Mega Factory",
    "interstellar-luxury_condo": "Alpha Luxury Condo",
    "interstellar-zoo": "Alpha Exotic Zoo",

    "interstellar-proxima_mission": "Proxima Mission",
    "interstellar-xfer_station": "Proxima Transfer Station",
    "interstellar-cargo_yard": "Proxima Cargo Yard",
    "interstellar-cruiser": "Proxima Patrol Cruiser",
    "interstellar-dyson": "Proxima Dyson Sphere (Adamantite)",
    "interstellar-dyson_sphere": "Proxima Dyson Sphere (Bolognium)",
    "interstellar-orichalcum_sphere": "Proxima Dyson Sphere (Orichalcum)",

    "interstellar-nebula_mission": "Nebula Mission",
    "interstellar-nexus": "Nebula Nexus",
    "interstellar-harvester": "Nebula Harvester",
    "interstellar-elerium_prospector": "Nebula Elerium Prospector",

    "interstellar-neutron_mission": "Neutron Mission",
    "interstellar-neutron_miner": "Neutron Miner",
    "interstellar-citadel": "Neutron Citadel Station",
    "interstellar-stellar_forge": "Neutron Stellar Forge",

    "interstellar-blackhole_mission": "Blackhole Mission",
    "interstellar-far_reach": "Blackhole Farpoint",
    "interstellar-stellar_engine": "Blackhole Stellar Engine",
    "interstellar-mass_ejector": "Blackhole Mass Ejector",

    "interstellar-jump_ship": "Blackhole Jump Ship",
    "interstellar-wormhole_mission": "Blackhole Wormhole Mission",
    "interstellar-stargate": "Blackhole Stargate",
    "interstellar-s_gate": "Blackhole Stargate (Complete)",

    "interstellar-sirius_mission": "Sirius Mission",
    "interstellar-sirius_b": "Sirius B Analysis",
    "interstellar-space_elevator": "Sirius Space Elevator",
    "interstellar-gravity_dome": "Sirius Gravity Dome",
    "interstellar-ascension_machine": "Sirius Ascension Machine",
    "interstellar-ascension_trigger": "Sirius Ascension Machine (Complete)",
    "interstellar-ascend": "Sirius Ascend",
    "interstellar-thermal_collector": "Sirius Thermal Collector",

    "galaxy-gateway_mission": "Gateway Mission",
    "galaxy-starbase": "Gateway Starbase",
    "galaxy-ship_dock": "Gateway Ship Dock",

    "galaxy-bolognium_ship": "Gateway Bolognium Ship",
    "galaxy-scout_ship": "Gateway Scout Ship",
    "galaxy-corvette_ship": "Gateway Corvette Ship",
    "galaxy-frigate_ship": "Gateway Frigate Ship",
    "galaxy-cruiser_ship": "Gateway Cruiser Ship",
    "galaxy-dreadnought": "Gateway Dreadnought",

    "galaxy-gateway_station": "Stargate Station",
    "galaxy-telemetry_beacon": "Stargate Telemetry Beacon",
    "galaxy-gateway_depot": "Stargate Depot",
    "galaxy-defense_platform": "Stargate Defense Platform",

    "galaxy-gorddon_mission": "Gorddon Mission",
    "galaxy-embassy": "Gorddon Embassy",
    "galaxy-dormitory": "Gorddon Dormitory",
    "galaxy-symposium": "Gorddon Symposium",
    "galaxy-freighter": "Gorddon Freighter",

    "galaxy-consulate": "Alien 1 Consulate",
    "galaxy-resort": "Alien 1 Resort",
    "galaxy-vitreloy_plant": "Alien 1 Vitreloy Plant",
    "galaxy-super_freighter": "Alien 1 Super Freighter",

    "galaxy-alien2_mission": "Alien 2 Mission",
    "galaxy-foothold": "Alien 2 Foothold",
    "galaxy-armed_miner": "Alien 2 Armed Miner",
    "galaxy-ore_processor": "Alien 2 Ore Processor",
    "galaxy-scavenger": "Alien 2 Scavenger",

    "galaxy-chthonian_mission": "Chthonian Mission",
    "galaxy-minelayer": "Chthonian Mine Layer",
    "galaxy-excavator": "Chthonian Excavator",
    "galaxy-raider": "Chthonian Corsair",

    "portal-turret": "Portal Laser Turret",
    "portal-carport": "Portal Surveyor Carport",
    "portal-war_droid": "Portal War Droid",
    "portal-repair_droid": "Portal Repair Droid",

    "portal-war_drone": "Badlands Predator Drone",
    "portal-sensor_drone": "Badlands Sensor Drone",
    "portal-attractor": "Badlands Attractor Beacon",

    "portal-pit_mission": "Pit Mission",
    "portal-assault_forge": "Pit Assault Forge",
    "portal-soul_forge": "Pit Soul Forge",
    "portal-gun_emplacement": "Pit Gun Emplacement",
    "portal-soul_attractor": "Pit Soul Attractor",
    "portal-soul_capacitor": "Pit Soul Capacitor (Witch Hunting)",
    "portal-absorption_chamber": "Pit Absorption Chamber (Witch Hunting)",

    "portal-ruins_mission": "Ruins Mission",
    "portal-guard_post": "Ruins Guard Post",
    "portal-vault": "Ruins Vault",
    "portal-archaeology": "Ruins Archaeology",
    "portal-arcology": "Ruins Arcology",
    "portal-hell_forge": "Ruins Infernal Forge",
    "portal-inferno_power": "Ruins Inferno Reactor",
    "portal-ancient_pillars": "Ruins Ancient Pillars",

    "portal-gate_mission": "Gate Mission",
    "portal-east_tower": "Gate East Tower",
    "portal-west_tower": "Gate West Tower",
    "portal-gate_turret": "Gate Turret",
    "portal-infernite_mine": "Gate Infernite Mine",

    "portal-lake_mission": "Lake Mission",
    "portal-harbour": "Lake Harbour",
    "portal-cooling_tower": "Lake Cooling Tower",
    "portal-bireme": "Lake Bireme Warship",
    "portal-transport": "Lake Transport",

    "portal-spire_mission": "Spire Mission",
    "portal-purifier": "Spire Purifier",
    "portal-port": "Spire Port",
    "portal-base_camp": "Spire Base Camp",
    "portal-bridge": "Spire Bridge",
    "portal-sphinx": "Spire Sphinx",
    "portal-bribe_sphinx": "Spire Bribe Sphinx",
    "portal-spire_survey": "Spire Survey Tower",
    "portal-mechbay": "Spire Mech Bay",
    "portal-spire": "Spire Tower",
    "portal-waygate": "Spire Waygate",

    "launch_facility": "Launch Facility",
    "lhc": "Supercollider",
    "stock_exchange": "Stock Exchange",
    "monument": "Monument",
    "railway": "Railway",
    "nexus": "Nexus",
    "roid_eject": "Asteroid Redirect",
    "syphon": "Mana Syphon",
    "tp_depot": "Depot",
}


TECH_NAMES = {
    "tech-wooden_tools": "Bone Tools",
    "tech-wooden_tools": "Wooden Tools",
    "tech-cottage": "Cottage",
    "tech-apartment": "Apartment",
    "tech-oil_power": "Oil Powerplant",
    "tech-oil_power": "Wind Farm",
    "tech-club": "Club",
    "tech-bone_tools": "Bone Tools",
    "tech-sundial": "Moondial",
    "tech-sundial": "Sundial",
    "tech-wheel": "Wheel",
    "tech-wagon": "Wagon",
    "tech-steam_engine": "Steam Engine",
    "tech-combustion_engine": "Combustion Engine",
    "tech-hover_cart": "Hover Cart",
    "tech-osha": "OSHA Regulations",
    "tech-blackmarket": "Blackmarket",
    "tech-pipelines": "Oil Pipelines",
    "tech-housing": "Housing",
    "tech-arcology": "Arcology",
    "tech-steel_beams": "Steel Beams",
    "tech-mythril_beams": "Mythril Beams",
    "tech-neutronium_walls": "Neutronium Walls",
    "tech-bolognium_alloy_beams": "Bolognium Alloy Beams",
    "tech-aphrodisiac": "Aphrodisiac",
    "tech-fertility_clinic": "Fertility Clinic",
    "tech-captive_housing": "Captive Housing",
    "tech-torture": "Torment",
    "tech-thrall_quarters": "Thrall Quarters",
    "tech-psychic_energy": "Psychic Energy",
    "tech-psychic_attack": "Psychic Assault",
    "tech-psychic_finance": "Psychic Finance",
    "tech-psychic_channeling": "Psychic Channeling",
    "tech-psychic_efficiency": "Psychic Efficiency",
    "tech-mind_break": "Psychic Mind Break",
    "tech-psychic_stun": "Psychic Stun",
    "tech-spear": "Flint Spear",
    "tech-bronze_spear": "Bronze Spear",
    "tech-iron_spear": "Iron Spear",
    "tech-dowsing_rod": "Dowsing Rod",
    "tech-metal_detector": "Metal Detector",
    "tech-smokehouse": "Smokehouse",
    "tech-lodge": "Hunting Lodge",
    "tech-alt_lodge": "Lodge",
    "tech-soul_well": "Soul Well",
    "tech-compost": "Composting",
    "tech-hot_compost": "Hot Composting",
    "tech-mulching": "Mulching",
    "tech-adv_mulching": "Advanced Mulching",
    "tech-agriculture": "Agriculture",
    "tech-farm_house": "Farm Houses",
    "tech-irrigation": "Irrigation",
    "tech-silo": "Grain Silo",
    "tech-mill": "Grain Mill",
    "tech-windmill": "Windmill",
    "tech-windturbine": "Wind Turbine",
    "tech-wind_plant": "Watermill",
    "tech-wind_plant": "Windmill",
    "tech-gmfood": "GM Food",
    "tech-foundry": "Foundry",
    "tech-artisans": "Artisans",
    "tech-apprentices": "Apprentices",
    "tech-carpentry": "Carpentry",
    "tech-demonic_craftsman": "Master Craftsman",
    "tech-master_craftsman": "Master Craftsman",
    "tech-brickworks": "Brickworks",
    "tech-machinery": "Machinery",
    "tech-cnc_machine": "CNC Machine",
    "tech-vocational_training": "Vocational Training",
    "tech-stellar_forge": "Stellar Forge",
    "tech-stellar_smelting": "Stellar Smelting",
    "tech-assembly_line": "Assembly Line",
    "tech-automation": "Factory Automation",
    "tech-laser_cutters": "Laser Cutters",
    "tech-high_tech_factories": "High-Tech Factory",
    "tech-theatre": "Theatre",
    "tech-playwright": "Playwright",
    "tech-magic": "Illusionists",
    "tech-magic": "Techno Wizards",
    "tech-superstars": "Super Stars",
    "tech-radio": "Radio",
    "tech-tv": "Television",
    "tech-vr_center": "VR Center",
    "tech-zoo": "Exotic Zoo",
    "tech-casino": "Casino",
    "tech-dazzle": "Extreme Dazzle",
    "tech-casino_vault": "Casino Vault",
    "tech-otb": "Off Track Betting",
    "tech-online_gambling": "Online Gambling",
    "tech-bolognium_vaults": "Bolognium Vault",
    "tech-mining": "Sap Hardening",
    "tech-mining": "Mining",
    "tech-bayer_process": "Bayer Process",
    "tech-elysis_process": "ELYSIS Process",
    "tech-smelting": "Smelting",
    "tech-steel": "Crucible Steel",
    "tech-blast_furnace": "Blast Furnace",
    "tech-bessemer_process": "Bessemer Process",
    "tech-oxygen_converter": "Oxygen Converter",
    "tech-electric_arc_furnace": "Electric Arc Furnace",
    "tech-hellfire_furnace": "Hellfire Furnace",
    "tech-infernium_fuel": "Infernium Fuel",
    "tech-iridium_smelting_perk": "Iridium Smelting",
    "tech-rotary_kiln": "Rotary Kiln",
    "tech-metal_working": "Metal Working",
    "tech-iron_mining": "Iron Mining",
    "tech-coal_mining": "Coal Mining",
    "tech-storage": "Basic Storage",
    "tech-reinforced_shed": "Reinforced Sheds",
    "tech-barns": "Barns",
    "tech-warehouse": "Warehouse",
    "tech-cameras": "Security Cameras",
    "tech-pocket_dimensions": "Pocket Dimensions",
    "tech-ai_logistics": "AI Shipping Logistics",
    "tech-containerization": "Containerization",
    "tech-reinforced_crates": "Reinforced Crates",
    "tech-cranes": "Cranes",
    "tech-titanium_crates": "Titanium-Banded Crates",
    "tech-mythril_crates": "Mythril-Plated Crates",
    "tech-infernite_crates": "Infernite Crates",
    "tech-graphene_crates": "Graphene Crates",
    "tech-bolognium_crates": "Bolognium Crates",
    "tech-steel_containers": "Steel Containers",
    "tech-gantry_crane": "Gantry Cranes",
    "tech-alloy_containers": "Alloy Containers",
    "tech-mythril_containers": "Mythril Containers",
    "tech-adamantite_containers": "Adamantite Containers",
    "tech-aerogel_containers": "Aerogel Containers",
    "tech-bolognium_containers": "Bolognium Containers",
    "tech-nanoweave_containers": "Nanoweave Liners",
    "tech-evil_planning": "Urban Planning",
    "tech-urban_planning": "Urban Planning",
    "tech-zoning_permits": "Zoning Permits",
    "tech-urbanization": "Urbanization",
    "tech-assistant": "Personal Assistant",
    "tech-government": "Government",
    "tech-theocracy": "Theocracy",
    "tech-republic": "Republic",
    "tech-socialist": "Socialist",
    "tech-corpocracy": "Corpocracy",
    "tech-technocracy": "Technocracy",
    "tech-federation": "Federation",
    "tech-magocracy": "Magocracy",
    "tech-governor": "Governor",
    "tech-spy": "Spies",
    "tech-espionage": "Espionage",
    "tech-spy_training": "Spy Training Facility",
    "tech-spy_gadgets": "Spy Gadgets",
    "tech-code_breakers": "Code Breakers",
    "tech-currency": "Currency",
    "tech-market": "Marketplace",
    "tech-tax_rates": "Tax Rates",
    "tech-large_trades": "Large Volume Trading",
    "tech-corruption": "Corrupt Politicians",
    "tech-massive_trades": "Massive Volume Trading",
    "tech-trade": "Trade Routes",
    "tech-diplomacy": "Diplomacy",
    "tech-freight": "Freight Trains",
    "tech-wharf": "Wharves",
    "tech-banking": "Banking",
    "tech-investing": "Investing",
    "tech-vault": "Bank Vault",
    "tech-bonds": "Savings Bonds",
    "tech-steel_vault": "Steel Vault",
    "tech-eebonds": "Series EE Bonds",
    "tech-swiss_banking": "Cheese Banking",
    "tech-safety_deposit": "Safety Deposit Box",
    "tech-stock_market": "Stock Exchange",
    "tech-hedge_funds": "Hedge Funds",
    "tech-four_oh_one": "401K",
    "tech-exchange": "Galactic Exchange",
    "tech-foreign_investment": "Foreign Investment",
    "tech-mythril_vault": "Mythril Vault",
    "tech-neutronium_vault": "Neutronium Vault",
    "tech-adamantite_vault": "Adamantite Vault",
    "tech-graphene_vault": "Graphene Vault",
    "tech-home_safe": "House Safe",
    "tech-fire_proof_safe": "Fire Proof Safe",
    "tech-tamper_proof_safe": "Tamper Proof Safe",
    "tech-monument": "Monuments",
    "tech-tourism": "Tourism",
    "tech-xeno_tourism": "Xeno Tourism",
    "tech-science": "Scientific Method",
    "tech-library": "Dewey Decimal System",
    "tech-thesis": "Thesis Papers",
    "tech-research_grant": "Research Grants",
    "tech-scientific_journal": "Magic Tomes",
    "tech-scientific_journal": "Scientific Journal",
    "tech-adjunct_professor": "Adjunct Professors",
    "tech-tesla_coil": "Tesla Coil",
    "tech-internet": "Internet",
    "tech-observatory": "Space Observatory",
    "tech-world_collider": "World Collider",
    "tech-laboratory": "Wizard Sanctum",
    "tech-laboratory": "Laboratory",
    "tech-virtual_assistant": "Virtual Assistant",
    "tech-dimensional_readings": "Dimensional Readings",
    "tech-quantum_entanglement": "Quantum Entanglement",
    "tech-expedition": "Magic Expeditions",
    "tech-expedition": "Scientific Expeditions",
    "tech-subspace_sensors": "Subspace Sensors",
    "tech-alien_database": "Alien Database",
    "tech-orichalcum_capacitor": "Orichalcum Capacitor",
    "tech-advanced_biotech": "Advanced Biotech",
    "tech-codex_infinium": "Codex Infinium",
    "tech-bioscience": "Bioscience",
    "tech-genetics": "Genetics",
    "tech-crispr": "CRISPR-Cas9",
    "tech-shotgun_sequencing": "Shotgun Sequencing",
    "tech-de_novo_sequencing": "De Novo Sequencing",
    "tech-dna_sequencer": "Code Sequencer",
    "tech-dna_sequencer": "DNA Sequencer",
    "tech-rapid_sequencing": "Agile Development",
    "tech-rapid_sequencing": "Rapid Gene Sequencing",
    "tech-mad_science": "Sages",
    "tech-mad_science": "Mad Science",
    "tech-electricity": "Electricity",
    "tech-matter_replicator": "Antimatter Replicator",
    "tech-matter_replicator": "Matter Replicator",
    "tech-industrialization": "Industrialization",
    "tech-electronics": "Electronics",
    "tech-fission": "Nuclear Fission",
    "tech-arpa": "A.R.P.A.",
    "tech-rocketry": "Rocketry",
    "tech-robotics": "Advanced Robotics",
    "tech-lasers": "Lasers",
    "tech-artifical_intelligence": "Artificial Intelligence",
    "tech-quantum_computing": "Quantum Computing",
    "tech-virtual_reality": "Virtual Reality",
    "tech-plasma": "Plasma Beams",
    "tech-shields": "Energy Shields",
    "tech-ai_core": "AI Supercore",
    "tech-metaphysics": "Metaphysics",
    "tech-orichalcum_analysis": "Orichalcum Analysis",
    "tech-cybernetics": "Cybernetics",
    "tech-blood_pact": "Blood Pact",
    "tech-purify": "Enhanced Air Filters",
    "tech-waygate": "Waygate",
    "tech-demonic_infusion": "Demonic Infusion",
    "tech-gate_key": "Gate Key",
    "tech-gate_turret": "Gate Turret",
    "tech-infernite_mine": "Infernite Survey",
    "tech-study_corrupt_gem": "Study Corrupt Gem",
    "tech-soul_binding": "Soul Binding",
    "tech-soul_capacitor": "Soul Capacitor",
    "tech-absorption_chamber": "Absorption Chamber",
    "tech-corrupt_gem_analysis": "Corrupt Gem Analysis",
    "tech-hell_search": "Search Hell Coordinates",
    "tech-codex_infernium": "Codex Infernium",
    "tech-lake_analysis": "Blood Lake Analysis",
    "tech-lake_threat": "Lake Threat",
    "tech-lake_transport": "Lake Transport",
    "tech-cooling_tower": "Cooling Tower",
    "tech-miasma": "Miasma",
    "tech-incorporeal": "Incorporeal Existence",
    "tech-tech_ascension": "Ascension",
    "tech-terraforming": "Terraforming",
    "tech-cement_processing": "Cement Processing",
    "tech-adamantite_processing_flier": "Adamantite Processing",
    "tech-adamantite_processing": "Adamantite Processing",
    "tech-graphene_processing": "Graphene Processing",
    "tech-fusion_power": "Nuclear Fusion",
    "tech-infernium_power": "Inferno Power",
    "tech-thermomechanics": "Thermomechanics",
    "tech-quantum_manufacturing": "Quantum Manufacturing",
    "tech-worker_drone": "Mining Drones",
    "tech-uranium": "Uranium Extraction",
    "tech-uranium_storage": "Uranium Storage",
    "tech-uranium_ash": "Uranium Ash",
    "tech-breeder_reactor": "Breeder Reactor",
    "tech-mine_conveyor": "Mine Conveyor Belts",
    "tech-oil_well": "Oil Derrick",
    "tech-oil_depot": "Fuel Depot",
    "tech-titanium_drills": "Titanium Drills",
    "tech-alloy_drills": "Alloy Drills",
    "tech-fracking": "Fracking",
    "tech-mythril_drills": "Mythril Drills",
    "tech-mass_driver": "Mass Driver",
    "tech-orichalcum_driver": "Orichalcum Mass Driver",
    "tech-polymer": "Polymer",
    "tech-fluidized_bed_reactor": "Fluidized Bed Reactor",
    "tech-synthetic_fur": "Faux Leather",
    "tech-synthetic_fur": "Synthetic Fur",
    "tech-nanoweave": "Nanoweave",
    "tech-stanene": "Stanene",
    "tech-nano_tubes": "Nano Tubes",
    "tech-scarletite": "Scarletite",
    "tech-pillars": "Pillars Research",
    "tech-reclaimer": "Reclaimers",
    "tech-shovel": "Shovel",
    "tech-iron_shovel": "Iron Shovel",
    "tech-steel_shovel": "Steel Shovel",
    "tech-titanium_shovel": "Titanium Shovel",
    "tech-alloy_shovel": "Alloy Shovel",
    "tech-mythril_shovel": "Mythril Shovel",
    "tech-adamantite_shovel": "Adamantite Shovel",
    "tech-stone_axe": "Primitive Axes",
    "tech-copper_axes": "Bronze Axe",
    "tech-iron_saw": "Sawmills",
    "tech-steel_saw": "Steel Saws",
    "tech-iron_axes": "Iron Axe",
    "tech-steel_axes": "Steel Axe",
    "tech-titanium_axes": "Titanium Axe",
    "tech-chainsaws": "Chainsaws",
    "tech-copper_sledgehammer": "Bronze Sledgehammer",
    "tech-iron_sledgehammer": "Iron Sledgehammer",
    "tech-steel_sledgehammer": "Steel Sledgehammer",
    "tech-titanium_sledgehammer": "Titanium Sledgehammer",
    "tech-copper_pickaxe": "Bronze Pickaxe",
    "tech-iron_pickaxe": "Iron Pickaxe",
    "tech-steel_pickaxe": "Steel Pickaxe",
    "tech-jackhammer": "Jackhammer",
    "tech-jackhammer_mk2": "Electric Jackhammer",
    "tech-adamantite_hammer": "Adamantite Jackhammer",
    "tech-copper_hoe": "Bronze Hoes",
    "tech-iron_hoe": "Iron Hoes",
    "tech-steel_hoe": "Steel Hoes",
    "tech-titanium_hoe": "Titanium Hoes",
    "tech-adamantite_hoe": "Adamantite Hoes",
    "tech-cyber_limbs": "Cybernetic Worker Limbs",
    "tech-slave_pens": "Slave Pens",
    "tech-slave_market": "Slave Market",
    "tech-ceremonial_dagger": "Ceremonial Dagger",
    "tech-last_rites": "Last Rites",
    "tech-ancient_infusion": "Ancient Infusion",
    "tech-garrison": "Garrison",
    "tech-mercs": "Mercenaries",
    "tech-signing_bonus": "Signing Bonus",
    "tech-hospital": "Hospital",
    "tech-bac_tanks": "Repair Subroutines",
    "tech-bac_tanks": "BAC Tank",
    "tech-boot_camp": "Boot Camp",
    "tech-vr_training": "VR Training",
    "tech-bows": "Bows",
    "tech-flintlock_rifle": "Magic Arrows",
    "tech-flintlock_rifle": "Flintlock Rifle",
    "tech-machine_gun": "Fire Mages",
    "tech-machine_gun": "Machine Gun",
    "tech-bunk_beds": "Bunk Beds",
    "tech-rail_guns": "Lightning Caster",
    "tech-rail_guns": "Rail Guns",
    "tech-laser_rifles": "Mana Rifles",
    "tech-laser_rifles": "Laser Rifles",
    "tech-plasma_rifles": "Focused Mana Rifles",
    "tech-plasma_rifles": "Plasma Rifles",
    "tech-disruptor_rifles": "Magic Missile",
    "tech-disruptor_rifles": "Disruptor Rifles",
    "tech-gauss_rifles": "Magic Word: Kill",
    "tech-gauss_rifles": "Gauss Rifles",
    "tech-cyborg_soldiers": "Cyborg Soldiers",
    "tech-space_marines": "Space Marines",
    "tech-hammocks": "Nanoweave Hammocks",
    "tech-cruiser": "Patrol Cruiser",
    "tech-armor": "Leather Armor",
    "tech-plate_armor": "Plate Armor",
    "tech-kevlar": "Kevlar",
    "tech-nanoweave_vest": "Nanoweave Vest",
    "tech-laser_turret": "Laser Turret",
    "tech-plasma_turret": "Plasma Turret",
    "tech-black_powder": "Magic Powder",
    "tech-black_powder": "Black Powder",
    "tech-dynamite": "Dynamite",
    "tech-anfo": "ANFO",
    "tech-mad": "Mutual Destruction",
    "tech-cement": "Cement",
    "tech-rebar": "Rebar",
    "tech-steel_rebar": "Steel Rebar",
    "tech-portland_cement": "Portland Cement",
    "tech-screw_conveyor": "Screw Conveyor",
    "tech-adamantite_screws": "Adamantite Screws",
    "tech-hunter_process": "Hunter Process",
    "tech-kroll_process": "Kroll Process",
    "tech-cambridge_process": "Cambridge Process",
    "tech-pynn_partical": "Pynn Particles",
    "tech-matter_compression": "Matter Compression",
    "tech-higgs_boson": "Higgs Boson",
    "tech-dimensional_compression": "Dimension Compression",
    "tech-theology": "Theology",
    "tech-fanaticism": "Fanaticism",
    "tech-alt_fanaticism": "Fanaticism",
    "tech-ancient_theology": "Ancient Theology",
    "tech-study": "Study Ancients",
    "tech-encoding": "Genetic Encoding",
    "tech-deify": "Deify Ancients",
    "tech-infusion": "Genetic Infusion",
    "tech-indoctrination": "Indoctrination",
    "tech-missionary": "Missionary",
    "tech-zealotry": "Zealotry",
    "tech-anthropology": "Anthropology",
    "tech-alt_anthropology": "Anthropology",
    "tech-mythology": "Mythology",
    "tech-archaeology": "Archaeology",
    "tech-merchandising": "Merchandising",
    "tech-astrophysics": "Astrophysics",
    "tech-rover": "Rovers",
    "tech-probes": "Space Probes",
    "tech-starcharts": "Star Charts",
    "tech-colonization": "Colonization",
    "tech-red_tower": "Red Control Tower",
    "tech-space_manufacturing": "Space Manufacturing",
    "tech-exotic_lab": "Exotic Materials Lab",
    "tech-hydroponics": "Hydroponics Bays",
    "tech-dyson_sphere": "Dyson Sphere",
    "tech-dyson_swarm": "Dyson Swarm",
    "tech-swarm_plant": "Swarm Plant",
    "tech-space_sourced": "Space Sourced",
    "tech-swarm_plant_ai": "Swarm Plant AI",
    "tech-swarm_control_ai": "Swarm Control AI",
    "tech-quantum_swarm": "Quantum Swarm",
    "tech-perovskite_cell": "Perovskite Cells",
    "tech-swarm_convection": "Swarm Convection",
    "tech-orichalcum_panels": "Orichalcum Panels",
    "tech-dyson_net": "Dyson Net",
    "tech-dyson_sphere2": "Dyson Sphere",
    "tech-orichalcum_sphere": "Orichalcum Dyson Plating",
    "tech-gps": "GPS Constellation",
    "tech-nav_beacon": "Navigation Beacon",
    "tech-subspace_signal": "Subspace Beacon",
    "tech-atmospheric_mining": "Atmospheric Mining",
    "tech-helium_attractor": "Helium Attractor",
    "tech-ram_scoops": "Ram Scoops",
    "tech-elerium_prospecting": "Elerium Prospecting",
    "tech-zero_g_mining": "Zero G Mining",
    "tech-elerium_mining": "Elerium Mining",
    "tech-laser_mining": "Laser Mining",
    "tech-plasma_mining": "Plasma Mining",
    "tech-elerium_tech": "Elerium Theory",
    "tech-elerium_reactor": "Elerium Reactor",
    "tech-neutronium_housing": "Neutronium Housing",
    "tech-unification": "Unification",
    "tech-unification2": "Unification",
    "tech-unite": "Unite Country",
    "tech-genesis": "Genesis Project",
    "tech-star_dock": "Space Dock",
    "tech-interstellar": "Interstellar Probes",
    "tech-genesis_ship": "Generational Ship",
    "tech-genesis_ship": "Genesis Ship",
    "tech-geck": "G.E.C.K.",
    "tech-genetic_decay": "Gene Therapy",
    "tech-stabilize_decay": "Stabilize Decay",
    "tech-tachyon": "Tachyon Particles",
    "tech-warp_drive": "Alcubierre Drive",
    "tech-habitat": "Habitat",
    "tech-graphene": "Graphene",
    "tech-aerogel": "Aerogel",
    "tech-mega_manufacturing": "Mega Manufacturing",
    "tech-luxury_condo": "Luxury Condo",
    "tech-stellar_engine": "Stellar Engine",
    "tech-mass_ejector": "Mass Ejector",
    "tech-asteroid_redirect": "Asteroid Redirect",
    "tech-exotic_infusion": "Exotic Infusion",
    "tech-infusion_check": "Exotic Infusion",
    "tech-infusion_confirm": "Exotic Infusion",
    "tech-stabilize_blackhole": "Stabilize Black Hole",
    "tech-veil": "The Veil",
    "tech-mana_syphon": "Mana Syphon",
    "tech-gravitational_waves": "Gravitational Waves",
    "tech-gravity_convection": "Gravitational Convection",
    "tech-wormholes": "Wormholes",
    "tech-portal": "Portals",
    "tech-fortifications": "Fortifications",
    "tech-war_drones": "War Drones",
    "tech-demon_attractor": "Demonic Attractor",
    "tech-combat_droids": "Combat Droids",
    "tech-repair_droids": "Repair Droids",
    "tech-advanced_predators": "Advanced Drones",
    "tech-enhanced_droids": "Enhanced War Droids",
    "tech-sensor_drone": "Sensor Drones",
    "tech-map_terrain": "Map Terrain",
    "tech-calibrated_sensors": "Calibrated Sensors",
    "tech-shield_generator": "Shield Generator",
    "tech-enhanced_sensors": "Enhanced Sensors",
    "tech-xeno_linguistics": "Xeno Linguistics",
    "tech-xeno_culture": "Xeno Culture",
    "tech-cultural_exchange": "Cultural Exchange",
    "tech-shore_leave": "Shore Leave",
    "tech-xeno_gift": "Alien Gift",
    "tech-industrial_partnership": "Industrial Partnership",
    "tech-embassy_housing": "Embassy Housing",
    "tech-advanced_telemetry": "Advanced Telemetry",
    "tech-defense_platform": "Defense Platform",
    "tech-scout_ship": "Scout Ship",
    "tech-corvette_ship": "Corvette Ship",
    "tech-frigate_ship": "Frigate Ship",
    "tech-cruiser_ship": "Cruiser Ship",
    "tech-dreadnought": "Dreadnought",
    "tech-ship_dock": "Ship Dock",
    "tech-ore_processor": "Ore Processor",
    "tech-scavenger": "Tech Scavenger",
    "tech-coordinates": "Decrypt Coordinates",
    "tech-chthonian_survey": "Chthonian Survey",
    "tech-gateway_depot": "Depot",
    "tech-soul_forge": "Soul Forge",
    "tech-soul_attractor": "Soul Attractor",
    "tech-soul_absorption": "Soul Absorption",
    "tech-soul_link": "Soul Link",
    "tech-gun_emplacement": "Gun Emplacement",
    "tech-advanced_emplacement": "Advanced Gun Emplacement",
    "tech-dial_it_to_11": "Dial it up to 11",
    "tech-limit_collider": "Limit Collider",
    "tech-mana": "Mana",
    "tech-ley_lines": "Ley Lines",
    "tech-rituals": "Rituals",
    "tech-crafting_ritual": "Crafting Rituals",
    "tech-mana_nexus": "Mana Nexus",
    "tech-clerics": "Clerics",
    "tech-conjuring": "Conjuring",
    "tech-res_conjuring": "Resource Conjuring",
    "tech-alchemy": "Alchemy",
    "tech-transmutation": "Advanced Transmutation",
    "tech-secret_society": "Secret Society",
    "tech-cultists": "Cultists",
    "tech-conceal_ward": "Concealing Wards",
    "tech-subtle_rituals": "Subtle Rituals",
    "tech-pylon_camouflage": "Pylon Camouflage",
    "tech-fake_tech": "Fake Tech",
    "tech-concealment": "Empowered Concealment Wards",
    "tech-improved_concealment": "Improved Concealment Wards",
    "tech-outerplane_summon": "Outerplane Summon",
    "tech-dark_bomb": "Dark Energy Bomb",
    "tech-bribe_sphinx": "Bribe Sphinx",
    "tech-alien_biotech": "Alien Biotech",
    "tech-zero_g_lab": "Zero Gravity Lab",
    "tech-operating_base": "Operating Base",
    "tech-munitions_depot": "Munitions Depot",
    "tech-fob": "Forward Operating Base",
    "tech-bac_tanks_tp": "BAC Tank",
    "tech-medkit": "Advanced Medkits",
    "tech-sam_site": "Planetary Defenses",
    "tech-data_cracker": "Data Cracker",
    "tech-ai_core_tp": "AI Supercore",
    "tech-ai_optimizations": "AI Optimizations",
    "tech-synthetic_life": "Synthetic Life",
    "tech-protocol66": "Protocol 66",
    "tech-protocol66a": "Protocol 66",
    "tech-terraforming_tp": "Terraforming",
    "tech-quantium": "Quantium",
    "tech-anitgrav_bunk": "Anti-Grav Bunks",
    "tech-higgs_boson_tp": "Higgs Boson",
    "tech-long_range_probes": "Long Range Probes",
    "tech-strange_signal": "Strange Signal",
    "tech-data_analysis": "Encrypted Data Analysis",
    "tech-mass_relay": "Mass Relay",
    "tech-nav_data": "Navigation Data",
    "tech-sensor_logs": "Tau Ceti Data",
    "tech-dronewar": "Drone Warfare",
    "tech-drone_tank": "AI Drone Tanks",
    "tech-stanene_tp": "Stanene",
    "tech-graphene_tp": "Graphene",
    "tech-virtual_reality_tp": "Virtual Reality",
    "tech-electrolysis": "Electrolysis",
    "tech-storehouse": "Titan Storage Facility",
    "tech-adamantite_vault_tp": "Adamantite Vault",
    "tech-titan_bank": "Titan Banking",
    "tech-hydrogen_plant": "Hydrogen Power",
    "tech-water_mining": "Water Mining",
    "tech-mercury_smelting": "Solar Smelting",
    "tech-iridium_smelting": "Iridium Smelting",
    "tech-adamantite_crates": "Adamantite Crates",
    "tech-bolognium_crates_tp": "Bolognium Crates",
    "tech-adamantite_containers_tp": "Adamantite Containers",
    "tech-quantium_containers": "Quantium Containers",
    "tech-unobtainium_containers": "Unobtainium Containers",
    "tech-reinforced_shelving": "Reinforced Shelving",
    "tech-garage_shelving": "Quantium Garage Shelving",
    "tech-warehouse_shelving": "Automated Warehousing System",
    "tech-elerium_extraction": "Elerium Extraction",
    "tech-orichalcum_panels_tp": "Orichalcum Panels",
    "tech-shipyard": "Dwarf Ship Yard",
    "tech-ship_lasers": "Ship Lasers",
    "tech-pulse_lasers": "Ship Pulse Lasers",
    "tech-ship_plasma": "Ship Plasma Beams",
    "tech-ship_phaser": "Ship Phasers",
    "tech-ship_disruptor": "Ship Disruptor",
    "tech-destroyer_ship": "Destroyer",
    "tech-cruiser_ship_tp": "Cruiser",
    "tech-h_cruiser_ship": "Battlecruiser",
    "tech-dreadnought_ship": "Dreadnought",
    "tech-pulse_engine": "Pulse Drive",
    "tech-photon_engine": "Photon Drive",
    "tech-vacuum_drive": "Vacuum Drive",
    "tech-ship_fusion": "Fusion Generator",
    "tech-ship_elerium": "Elerium Generator",
    "tech-quantum_signatures": "Quantum Signatures",
    "tech-interstellar_drive": "Interstellar Drive",
    "tech-alien_outpost": "Alien Outpost",
    "tech-jumpgates": "Jump Gates",
    "tech-system_survey": "Tau Survey",
    "tech-repository": "Repository",
    "tech-fusion_generator": "Nuclear Fusion",
    "tech-tau_cultivation": "Tau Ceti Cultivation",
    "tech-tau_manufacturing": "Tau Ceti Manufacturing",
    "tech-weasels": "Weasels",
    "tech-jeff": "Contact Jeff",
    "tech-womling_fun": "Womling Entertainment",
    "tech-womling_lab": "Womling Science",
    "tech-womling_mining": "Womling Dirt Excavation",
    "tech-womling_firstaid": "Womling First Aid",
    "tech-womling_logistics": "Womling Logistics",
    "tech-womling_repulser": "Womling Repulser Pad",
    "tech-womling_farming": "Womling Farming",
    "tech-womling_housing": "Womling Housing",
    "tech-womling_support": "Womling Support",
    "tech-womling_recycling": "Womling Recycling",
    "tech-asteroid_analysis": "Asteroid Data Analysis",
    "tech-shark_repellent": "Shark Repellent",
    "tech-belt_mining": "Tau Ceti Belt Mining",
    "tech-adv_belt_mining": "Advanced Belt Mining",
    "tech-space_whaling": "Space Whaling",
    "tech-infectious_disease_lab": "Malicious Code Lab",
    "tech-infectious_disease_lab": "Infectious Disease Lab",
    "tech-isolation_protocol": "Isolation Protocol",
    "tech-focus_cure": "Focus Cure",
    "tech-decode_virus": "Decode Virus",
    "tech-vaccine_campaign": "Vaccination Campaign",
    "tech-vax_strat1": "Propaganda Campaign",
    "tech-vax_strat2": "Force Vaccination",
    "tech-vax_strat3": "Show the Science",
    "tech-vax_strat4": "Secret Vaccination",
    "tech-cloning": "Cloning Facility",
    "tech-clone_degradation": "Clone Degradation",
    "tech-digital_paradise": "Digital Paradise",
    "tech-ringworld": "Design a Ringworld",
    "tech-iso_gambling": "Pit Bosses",
    "tech-outpost_boost": "Alien Outpost Device",
    "tech-cultural_center": "Cultural Center",
    "tech-outer_tau_survey": "Survey Outer Planet",
    "tech-alien_research": "Alien Research",
    "tech-womling_gene_therapy": "Womling Gene Therapy",
    "tech-food_culture": "Sell fruitcake",
    "tech-advanced_refinery": "Advanced Ore Refinery",
    "tech-advanced_pit_mining": "Advanced Pit Mining",
    "tech-useless_junk": "Useless Junk",
    "tech-advanced_asteroid_mining": "Advanced Asteroid Mining",
    "tech-advanced_material_synthesis": "Advanced Material Synthesis",
    "tech-matrioshka_brain": "Matrioshka Brain",
    "tech-ignition_device": "Ignition Device",
    "tech-replicator": "Antimatter Replicator",
    "tech-replicator": "Matter Replicator",
    "tech-womling_unlock": "Meet The Neighbors",
    "tech-garden_of_eden": "Garden of Eden",
}
